server:
  port: 317
  tomcat:
    uri-encoding: utf-8
    #初始化线程数20
    min-spare-threads: 20
    #最大线程数1000
    max-threads: 1000
    #超时时间是5000ms
    max-connections: 5000
spring:
  security:
    base:
      enabled: false
    user:
      name: admin
      password: shengxi
      roles:
        - user
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    sql-script-encoding: utf-8
    driverClassName: com.mysql.jdbc.Driver
    druid:
      # 主库数据源
      master:
        url: jdbc:mysql://47.106.188.177:3306/rs?useUnicode=true&characterEncoding=utf8&useServerPstmts=true&cachePrepStmts=true&allowMultiQueries=true&autoReconnect=true&failOverReadOnly=false&cacheCallableStmts=true&connectTimeout=1000&maxReconnects=5&zeroDateTimeBehavior=convertToNull&useSSL=true
        username: root
        password: 1234567
      # 从库数据源
      slave:
        # 从数据源开关/默认关闭
        enabled: true
        url: jdbc:mysql://47.106.188.177:3306/rs?useUnicode=true&characterEncoding=utf8&useServerPstmts=true&cachePrepStmts=true&allowMultiQueries=true&autoReconnect=true&failOverReadOnly=false&cacheCallableStmts=true&connectTimeout=1000&maxReconnects=5&zeroDateTimeBehavior=convertToNull&useSSL=true
        username: reader
        password: reader
      connect-properties:
        druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
      # 初始连接数
      initialSize: 10
      # 最大连接池数量
      maxActive: 50
      # 最小连接池数量
      minIdle: 10
      # 配置获取连接等待超时的时间
      maxWait: 60000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      timeBetweenEvictionRunsMillis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      minEvictableIdleTimeMillis: 300000
      # 配置一个连接在池中最大生存的时间，单位是毫秒
      maxEvictableIdleTimeMillis: 900000
      # 配置检测连接是否有效
      validationQuery: SELECT 1 FROM DUAL
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      webStatFilter:
        enabled: true
      statViewServlet:
        enabled: true
        url-pattern: /monitor/druid/*
      filter:
        stat:
          enabled: true
          log-slow-sql: true
          slow-sql-millis: 1000
          merge-sql: false
        wall:
          config:
            multi-statement-allow: true
        log4j:
          statement-logger-name:
  mvc:
    favicon:
      enabled: false
    view:
      prefix: /templates
      suffix: .html

  redis:
    # Redis数据库索引（默认为0）
    database: 0
    # Redis服务器地址
    host: 47.106.188.177
    # Redis服务器连接端口
    port: 6379
    # Redis 密码
    password: "1234567"
    jedis:
      pool:
        # 连接池中的最小空闲连接
        min-idle: 8
        # 连接池中的最大空闲连接
        max-idle: 500
        # 连接池最大连接数（使用负值表示没有限制）
        max-active: 2000
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: 10000
    # 连接超时时间（毫秒）
    timeout: 30000


  thymeleaf:
    cache: false

  aop:
    proxy-target-class: true
  cache:
    type:
      redis

  devtools:
    restart:
      enabled: true

jasypt:
  encryptor:
    password: shengxi

mybatis:
  # type-aliases扫描路径
  type-aliases-package: com.shengxi.system.entites
    # 配置mapper的扫描，找到所有的mapper.xml映射文件
  mapper-locations:
    - classpath*:mapper/**/*Mapper.xml
    # 加载全局的配置文件
  config-location: classpath:mapper/mybatis-config.xml


mapper:
  not-empty: true
  identity: MYSQL


pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

#token过期时间
token:
  expire:
    seconds: 7200
  jwtSecret: (RS:) _$^11277^$&_(SHENG:)_@@++--(XI:)_++++_.sds_(LEUNG)

# rs 配置
rs:
  # 是否在控制台打印 sql语句
  showsql: true
  # 时间类型参数在前端页面的展示格式，默认格式为 yyyy-MM-dd HH:mm:ss
  timeFormat: yyyy-MM-dd HH:mm:ss
  # 是否开启 AOP 日志，默认开启
  openAopLog: true