server:
  tomcat:
    uri-encoding: utf-8
    #初始化线程数20
    min-spare-threads: 20
    #最大线程数1000
    max-threads: 1000
    #超时时间是5000ms
    max-connections: 5000
spring:
  profiles:
    active: local
  security:
    base:
      enabled: false
    user:
      name: admin
      password: shengxi
      roles:
      - user
  mvc:
    favicon:
      enabled: false
    view:
      prefix: /templates
      suffix: .html
  redis:
    # Redis数据库索引（默认为0）
    database: 0
    # Redis服务器地址
    host: "47.106.188.177"
    # Redis服务器连接端口
    port: 6379
    # Redis 密码
    password: "shengxi"
    jedis:
      pool:
        # 连接池中的最小空闲连接
        min-idle: 8
        # 连接池中的最大空闲连接
        max-idle: 500
        # 连接池最大连接数（使用负值表示没有限制）
        max-active: 2000
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: 10000
    # 连接超时时间（毫秒）
    # 两个小时
    timeout: 7200000
  thymeleaf:
    cache: false

  aop:
    proxy-target-class: true
  cache:
    type:
      redis

  devtools:
    restart:
      enabled: true
jasypt:
  encryptor:
    password: shengxi
mybatis:
  # type-aliases扫描路径
  type-aliases-package: com.shengxi.system.entites
  # 配置mapper的扫描，找到所有的mapper.xml映射文件
  mapper-locations:
  - classpath*:mapper/**/*Mapper.xml
  # 加载全局的配置文件
  config-location: classpath:mapper/mybatis-config.xml
mapper:
  not-empty: true
  identity: MYSQL
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
#token过期时间
#两个小时
token:
  expire:
    seconds: 7200
  jwtSecret: (RS:) _$^172179^$&_(SHENG:)_@@++--(XI:)_++++_.sds_(LEUNG)
jwt:
  auth:
    path: /login
# rs 配置
rs:
  # 是否在控制台打印 sql语句
  showSql: true
  # 时间类型参数在前端页面的展示格式，默认格式为 yyyy-MM-dd HH:mm:ss
  timeFormat: yyyy-MM-dd HH:mm:ss
  # 是否开启 AOP 日志，默认开启
  openAopLog: true