package com.shengxi.rs.common.config;

import com.shengxi.rs.common.domain.BaseEntity;
import com.shengxi.rs.common.domain.SysRole;
import org.springframework.security.core.GrantedAuthority;
import org.springframework.security.core.authority.SimpleGrantedAuthority;
import org.springframework.security.core.userdetails.UserDetails;

import java.util.ArrayList;
import java.util.Collection;
import java.util.Date;
import java.util.List;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table sys_user
 *
 * @mbg.generated do_not_delete_during_merge
 */
@SuppressWarnings("serial")
public class SysUser extends BaseEntity implements UserDetails {
    /**
     * Database Column Remarks:
     *   用户ID
     */
    private String userId;

    /**
     * Database Column Remarks:
     *   用户名
     */
    private String userName;

    /**
     * Database Column Remarks:
     *   密码
     */
    private String passWord;

    /**
     * Database Column Remarks:
     *   部门ID
     */
    private Long deptId;

    /**
     * Database Column Remarks:
     *   状态 0锁定 1有效
     */
    private String status;


    /**
     * Database Column Remarks:
     *   最近访问时间
     */
    private Date loginTime;

    /**
     * Database Column Remarks:
     *   性别 0男 1女
     */
    private String userSex;

    /**
     * Database Column Remarks:
     *   专业
     */
    private String major;

    private List<SysRole> roles;

    public String getUserId() {
        return userId;
    }

    public void setUserId(String userId) {
        this.userId = userId;
    }

    public String getUserName() {
        return userName;
    }

    public void setUserName(String userName) {
        this.userName = userName;
    }

    public String getPassWord() {
        return passWord;
    }

    public void setPassWord(String passWord) {
        this.passWord = passWord;
    }

    public Long getDeptId() {
        return deptId;
    }

    public void setDeptId(Long deptId) {
        this.deptId = deptId;
    }

    public String getStatus() {
        return status;
    }

    public void setStatus(String status) {
        this.status = status;
    }

    public Date getLoginTime() {
        return loginTime;
    }

    public void setLoginTime(Date loginTime) {
        this.loginTime = loginTime;
    }

    public String getUserSex() {
        return userSex;
    }

    public void setUserSex(String userSex) {
        this.userSex = userSex;
    }

    public String getMajor() {
        return major;
    }

    public void setMajor(String major) {
        this.major = major;
    }

    @Override
    public String toString() {
        return "SysUser{" +
                "userId='" + userId + '\'' +
                ", userName='" + userName + '\'' +
                ", passWord='" + passWord + '\'' +
                ", deptId=" + deptId +
                ", status='" + status + '\'' +
                ", loginTime=" + loginTime +
                ", userSex='" + userSex + '\'' +
                ", major='" + major + '\'' +
                '}';
    }

    @Override
    public Collection<? extends GrantedAuthority> getAuthorities() {
        List<GrantedAuthority> auths = new ArrayList<>();
        List<SysRole> roles = this.roles;
        for (SysRole role : roles){
            auths.add(new SimpleGrantedAuthority(role.getUserName()));
        }
        return auths;
    }

    @Override
    public String getPassword() {
        return passWord;
    }

    @Override
    public String getUsername() {
        return userName;
    }

    @Override
    public boolean isAccountNonExpired() {
        return false;
    }

    @Override
    public boolean isAccountNonLocked() {
        return true;
    }

    @Override
    public boolean isCredentialsNonExpired() {
        return true;
    }

    @Override
    public boolean isEnabled() {
        return true;
    }
}